server:
   port: 8080
spring:
   application:
      name: jasypt
   datasource:
      url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: ENC(3ad12c83f02dda026e992b0af57f774a)
# 加密配置
jasypt:
  encryptor:
    # SM4密钥（32位十六进制字符串）
    sm4-key: 6925d1c489ba52ef021d00bd5eb31875
    # 加密类 
    bean: jasyptStringEncryptor

## SpringDoc 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 标签排序方式
    tags-sorter: alpha
    # 操作排序方式
    operations-sorter: alpha
    # 保持认证状态
    persistAuthorization: true
    # 隐藏models
    default-models-expand-depth: -1
  packages-to-scan: net.xzh.jasypt
  paths-to-match: /**