server:
  port: 8080
spring:
  application:
    name: mqtt-paho
    
mqtt:
  broker-url: tcp://172.17.17.161:1883
  client-id: java-server-paho
  username: admin
  password: 123456
  cleanSession: true
  reconnect: true
  timeout: 1000
  keepAlive: 100
  defaultTopic: testtopic
  qos: 2