server:
   port: 8080

## SpringDoc 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 标签排序方式
    tags-sorter: alpha
    # 操作排序方式
    operations-sorter: alpha
    # 保持认证状态
    persistAuthorization: true
    # 隐藏models
    default-models-expand-depth: -1
  packages-to-scan: net.xzh.fisco
  paths-to-match: /**

fisco:
  cryptoMaterial:
    certPath: "conf"

  network:
    peers:
      - "172.17.17.161:20200"

  amop:
    #  - publicKeys: [ "conf/amop/consumer_public_key_1.pem" ]
    #    topicName: "PrivateTopic1"
    #  - password: "123456"
    #    privateKey: "conf/amop/consumer_private_key.p12"
    #    topicName: "PrivateTopic2"

    account:
      keyStoreDir: "account"
      accountFilePath: ""
      accountFileFormat: "pem"
      password: ""
      accountAddress: ""

    threadPool:
      channelProcessorThreadSize: "16"
      receiptProcessorThreadSize: "16"
      maxBlockingQueueSize: "102400"