server:
  port: 8080

spring:
  application:
    name: xzh-oss
  datasource:
    url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
   
logging:
  level:
    root: info
    net.xzh: debug
    
xzh:
  file-server:
    type: s3
    fdfs:
      web-url: http://172.17.17.161
    s3:
      access-key: minioadmin
      accessKeySecret: minioadmin
      endpoint: http://172.17.17.161:9000
      bucketName: test
fdfs: 
   trackerList: 172.17.17.161:22122