server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: 172.17.17.192 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 16380 # Redis服务器连接端口
    password: 'redis16380'  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间
    #sentinel:
      #master: mymaster
      #nodes: 192.168.3.200:26379,192.168.3.200:26380,192.168.3.200:26381  
    #cluster:
      #nodes: 192.168.3.201:26379,192.168.3.201:26380,192.168.3.201:26381,192.168.3.201:6379,192.168.3.201:6380,192.168.3.201:6381
redis:
  cache:
    configs:
      - key: mall:brand
        second: 1800
      - key: mall:order
        second: 36000
logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

## SpringDoc 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 标签排序方式
    tags-sorter: alpha
    # 操作排序方式
    operations-sorter: alpha
    # 保持认证状态
    persistAuthorization: true
    # 隐藏models
    default-models-expand-depth: -1
  packages-to-scan: net.xzh.redis
  paths-to-match: /**
