server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

spring:
   application:
      name: pg-jmeter
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://172.17.17.57:5432/vjsp_base
      username: vjsp_base
      password: Ps6RB4oxjKdauxol
      hikari:
         # 连接池核心参数
         maximum-pool-size: 20              # 最大连接数
         minimum-idle: 5                    # 最小连接数
         # 连接有效性检查
         connection-timeout: 30000          # 连接超时时间（默认30秒）
         idle-timeout: 600000               # 空闲连接最大存活时间（默认:10分钟）
         max-lifetime: 1800000              # 连接最大生命周期（30分钟），小于pg的tcp_keepalive时间
         # 优化参数
         leak-detection-threshold: 5000     # 连接泄漏检测阈值（毫秒）
         pool-name: hikari                  # 连接池名
         auto-commit: true                  # 自动提交
         validation-timeout: 5000           # 连接验证超时