server:
   port: 8080

spring:
  rabbitmq:
    addresses: 172.17.17.161:5672
    virtual-host: /
    username: admin
    password: 123456

minio:
  endpoint: http://172.17.17.161:9000/ #Minio服务所在地址
  bucketName: test #存储桶名称
  accessKey: t2JpWqEEKbOhhGADx4hW #访问的key
  secretKey: K6CZqKgRY2PWBzZx41W9SfhCr2ZcrMGgPRFCvNWw #访问的秘钥