server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:d:/test.db
    username: 
    password:
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update
