# 熔断器和限流

### 重试：调用失败最多5次，每次间隔1秒
GET http://127.0.0.1:8080/retry

### 熔断器：当调用量达到5次且失败率超过20%时，断路器会进入开路状态并持续5秒，之后进入半开状态允许试探性调用3次来检测服务是否恢复
GET http://127.0.0.1:8080/circuitbreaker

### 限流：1秒内最多只能调用1次
GET http://127.0.0.1:8080/flowlimit

### 限流：1秒内最多只能调用1次
GET http://127.0.0.1:8080/bulkhead