server:
   port: 8080
spring:
   mail:
      host: smtp.163.com
      username: xcg992224
      password: FWjnmu7CF2TdEc8T
      default-encoding: UTF-8
      fromAddr: xcg992224@163.com
      nickName: young