spring:
  datasource:
    url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌前缀
  prefix: "Bearer "
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expiration: 1800


## SpringDoc 配置
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    # 标签排序方式
    tags-sorter: alpha
    # 操作排序方式
    operations-sorter: alpha
    # 保持认证状态
    persistAuthorization: true
    # 隐藏models
    default-models-expand-depth: -1
  packages-to-scan: net.xzh.security
  paths-to-match: /**

# 安全路径白名单
secure:
  ignored:
    urls:
      - /swagger-ui/**
      - /api-docs/**
      - /favicon.ico
      - /jwt/**
      - /register
      - /login
