# 自定义分布式文件存储

### 上传附件
POST http://127.0.0.1:8080/files-anon
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpeg

< d:/1791.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### 删除附件
DELETE http://127.0.0.1:8080/files/97ea676266574bb880115446c62f2063
