spring:
  datasource:
    # 多数据源切换
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://172.17.17.137:3306/mall?serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          url: jdbc:mysql://172.17.17.137:3306/mall_tiny?serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver