server:
   port: 8080
spring:
   application:
      name: hikaricp
   datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      hikari:
         # 连接池核心参数
         maximum-pool-size: 20              # 最大连接数
         minimum-idle: 5                    # 最小连接数
         # 连接有效性检查
         connection-timeout: 30000          # 连接超时时间（默认30秒）
         idle-timeout: 600000               # 空闲连接最大存活时间（默认:10分钟）
         max-lifetime: 1800000              # 连接最大生命周期（30分钟），小于pg的tcp_keepalive时间
         # 优化参数
         leak-detection-threshold: 5000     # 连接泄漏检测阈值（毫秒）
         pool-name: hikari                  # 连接池名
         auto-commit: true                  # 自动提交
         validation-timeout: 5000           # 连接验证超时