spring:
  datasource:
    url: jdbc:mysql://172.17.17.137:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
  redis:
    host: 172.17.17.192 # Redis服务器地址
    database: 1 # Redis数据库索引（默认为0）
    port: 16380 # Redis服务器连接端口
    password: 'redis16380'  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间

redis:
  cache:
    configs:
      - key: mall:brand
        second: 1800
      - key: mall:order
        second: 36000
  database: mall
  key:
    admin: 'ums:admin'
    resourceList: 'ums:resourceList'
  expire:
    common: 86400 # 24小时



rabbitmq:
  relayHost: 172.17.17.161
  relayPort: 61613
  virtualHost: /
  login: admin
  passcode: 123456

token:
  # 令牌自定义标识
  header: Authorization
  # 令牌前缀
  prefix: "Bearer "
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expiration: 1800

# 安全路径白名单
secure:
  ignored:
    urls:
      - /swagger-ui/**
      - /api-docs/**
      - /favicon.ico
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /ws/**
      - /login