### 动态脚本，从容器中自动获取
POST http://127.0.0.1:8080/groovy/script/execute
Content-Type: application/json

import net.xzh.groovy.model.User;
import net.xzh.groovy.service.UserService;
import java.util.List;
import java.util.Random;

// 直接使用已注入的testService变量
def userList = userService.list;

// 方法执行
if(userList == null || userList.size() == 0){
    userService.getUser();
    userList = userService.list;
}

for (def i = 0; i < userList.size(); i++) {
    // 根据年龄配置随机数
    if(userList.get(i).getAge() < 25){
        userList.get(i).setRandom(new Random().nextInt(10));
    } else {
        userList.get(i).setRandom(new Random().nextInt(20) + new Random().nextInt(10));
    }
}
userService.sendDataS(userList);

return "执行成功";


### 动态脚本，从容器中手动获取
POST http://127.0.0.1:8080/groovy/script/execute
Content-Type: application/json

import net.xzh.groovy.model.User;
import net.xzh.groovy.service.UserService;
import java.util.List;
import java.util.Random;

// 使用SpringContextUtil获取UserService
UserService userService = SpringContextUtil.getBean(UserService.class);

def userList = userService.list;

// 方法执行
if(userList == null || userList.size() == 0){
    userService.getUser();
    userList = userService.list;
}

for (def i = 0; i < userList.size(); i++) {
    // 根据年龄配置随机数
    if(userList.get(i).getAge() < 25){
        userList.get(i).setRandom(new Random().nextInt(10));
    } else {
        userList.get(i).setRandom(new Random().nextInt(20) + new Random().nextInt(10));
    }
}
userService.sendDataS(userList);

return "执行成功";