spring:
   thymeleaf:
      enabled: true
      cache: false
      encoding: UTF-8
      prefix: classpath:/templates/
      suffix: .html
   messages:
      basename: i18n.messages
      encoding: utf-8

secure:
  ignored:
    urls:
      - /
      - /error
      - /webjars/**
      - /images/**
      - /js/**
      - /css/**
      - /plugins/**
      - /login
      - /user/**
