server:
  port: 8080
spring:
  rabbitmq:
    addresses: 172.17.17.161:5672
    virtual-host: /xzh  # 虚拟host
    username: admin     # 用户名
    password: 123456    # 密码
    listener:
      simple:  
        acknowledge-mode: manual	# 手动确认模式
        concurrency: 3     		# 最小消费者数量
        max-concurrency: 10 	# 最大消费者数量
        prefetch: 250        	# 默认预取数量
      direct:
        acknowledge-mode: manual
