server:
  port: 8080

spring:
  application:
    name: activemq
  jms:
    pub-sub-domain: false
    template:
      delivery-mode: persistent
  activemq:
    broker-url: tcp://172.17.17.161:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
      max-connections: 10
      # 空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      # 强制的连接过期时间
      expiry-timeout: 0
