sharding:
  jdbc:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbcUrl: jdbc:postgresql://172.17.17.161:5432/ec_demo_0?useUnicode=true&characterEncoding=utf8&currentSchema=public&stringtype=unspecified
        username: postgres
        password: postgres
    config:
      sharding:
        tables:
          user_info:
            actual-data-nodes: ds.user_info$->{0..1}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: user_info$->{id % 2}
            key-generator-column-name: id
      props:
        sql:
          show: true